---
- hosts: all
  become: true

  tasks:

  - name: stop current running container
    command: docker stop simple-devops-container  # this will stop currently running container
    ignore_errors: yes  ## this will ingore if t here is no container is running

  - name: remove stopped container
    command: docker rm simple-devops-container  # this will delete container
    ignore_errors: yes   # ignore if there is no container to delete

  - name: remove docker image
    command: docker rmi simple-devops-image
    ignore_errors: yes   # ignore errors if no images to delete

  - name: build docker image using war file
    command: docker build -t simple-devops-image .
    args:
      chdir: /opt/docker

  - name: create container using simple-devops-image
    command: docker run -d --name simple-devops-container -p 8080:8080  simple-devops-image
